<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link href="/css/style.css" rel="stylesheet"  type="text/css" />
</head>
<body>
    <div class = "container">
        <div class = "inner">
            <textarea id="code_snippet">// write your code here</textarea>
            <button id="send_snippet" type="submit" onclick="send()">Submit</button>
        </div>
    </div>
</body>
<script type="text/javascript" src="/js/sendScript.js"></script>
</html>